ZubiArticleBundle_homepage:
    pattern:  /
    defaults: { _controller: ZubiArticleBundle:Default:index }
    
ZubiArticleBundle_showarticle:
    pattern:  /show/{id}
    defaults: { _controller: ZubiArticleBundle:Default:showArticle }
    
ZubiArticleBundle_add:
    pattern:  /add/
    defaults: { _controller: ZubiArticleBundle:Default:add }    
    
