parameters:
#    zubi_article.example.class: Zubi\ArticleBundle\Example

services:
#    zubi_article.example:
#        class: %zubi_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
