ZubiUserBundle_private:
    pattern:  /private
    defaults: { _controller: ZubiUserBundle:Private:private }

ZubiUserBundle_register:
    pattern:  /register
    defaults: { _controller: ZubiUserBundle:Register:register }

ZubiUserBundle_login:
    pattern:  /login
    defaults: { _controller: ZubiUserBundle:Login:login }

ZubiUserBundle_homepage:
    pattern:  /
    defaults: { _controller: ZubiUserBundle:Default:index }