Zubi\UserBundle\Entity\User:
    type: entity
    table: uzytkownicy
    id:
        id:
            type: integer
            length: 10
            generator: { strategy: AUTO }
    fields:
        haslo:
            type: string
            length: 255
        email:
            type: string
            length: 255
        osoba_prezentacja:
            type: integer
            length: 1
        kraj:
            type: string
            length: 255
        kraj_prezentacja:
            type: integer
            length: 1
        miasto:
            type: string
            length: 255
        miasto_prezentacja:
            type: integer
            length: 1
        data_ur:
            type: date
        data_ur_prezentacja:
            type: integer
            length: 1
    manyToOne:
        id_status:
            targetEntity: Status
            inversedBy: users
            joinColumn:
                name: id_status
                referencedColumnName: id