ZubiUserBundle:
    resource: "@ZubiUserBundle/Resources/config/routing.yml"
    prefix:   /profile

ZubiFaqBundle:
    resource: "@ZubiFaqBundle/Resources/config/routing.yml"
    prefix:   /faq

ZubiDeviceBundle:
    resource: "@ZubiDeviceBundle/Resources/config/routing.yml"
    prefix:    /device

ZubiIndexBundle:
    resource: "@ZubiIndexBundle/Resources/config/routing.yml"
    prefix:   /

ZubiUserBundle_login:
    pattern:  /login
    defaults: { _controller: ZubiUserBundle:Login:login }

ZubiUserBundle_login_check:
    pattern:   /login_check

ZubiUserBundle_logout:
    pattern:   /logout


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
