ZubiFaqBundle:
    resource: "@ZubiFaqBundle/Resources/config/routing.yml"
    prefix:   /faq

ZubiProfileBundle:
    resource: "@ZubiProfileBundle/Resources/config/routing.yml"
    prefix:   /profile

ZubiDeviceBundle:
    resource: "@ZubiDeviceBundle/Resources/config/routing.yml"
    prefix:   /device

ZubiRegisterBundle:
    resource: "@ZubiRegisterBundle/Resources/config/routing.yml"
    prefix:   /register

ZubiLoginBundle:
    resource: "@ZubiLoginBundle/Resources/config/routing.yml"
    prefix:   /login

ZubiIndexBundle:
    resource: "@ZubiIndexBundle/Resources/config/routing.yml"
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
