ZubiProfileBundle_homepage:
    pattern:  /
    defaults: { _controller: ZubiProfileBundle:Default:index }


ZubiProfileBundle_private:
    pattern:  /private
    defaults: { _controller: ZubiProfileBundle:Default:private }