parameters:
#    zubi_profile.example.class: Zubi\ProfileBundle\Example

services:
#    zubi_profile.example:
#        class: %zubi_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
