ZubiDeviceBundle_homepage:
    pattern:  /stations
    defaults: { _controller: ZubiDeviceBundle:Station:index }

ZubiDeviceBundle_collect:
    pattern: /collect/{stationHash}/{measurementType}/{measurementValue}
    defaults: { _controller: ZubiDeviceBundle:Station:collect }

ZubiDeviceBundle_addStation:
    pattern: /add-station
    defaults: { _controller: ZubiDeviceBundle:Station:addStation }

ZubiDeviceBundle_measurements:
    pattern: /measurements/{station}
    defaults: { _controller: ZubiDeviceBundle:Measurement:index, station: false }