ZubiDeviceBundle_homepage:
    pattern:  /
    defaults: { _controller: ZubiDeviceBundle:Default:index }

ZubiDeviceBundle_collect:
    pattern: /collect/{stationHash}/{measurementType}/{measurementValue}
    defaults: { _controller: ZubiDeviceBundle:Default:collect}