Zubi\ArticleBundle\Entity\ArticleGroup:
  type: entity
  table: status_widocznosci
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: '255'
      column: Nazwa
  lifecycleCallbacks: {  }
  oneToMany:
    articles:        
      targetEntity: Article
      mappedBy: id_grupy
