Zubi\DeviceBundle\Entity\Measurement:
  type: entity
  table: Pomiary
  fields:
    id:
      type: integer
      id: true
      column: Id
      generator:
        strategy: AUTO
    stationId:
      type: integer
      column: Id_Stacji
    timestamp:
      type: datetime
      column: Czas
    value:
      type: float
      column: Wartosc
  lifecycleCallbacks: {  }
  manyToOne:
    station:
      targetEntity: Station
      inversedBy: measurements
      joinColumn:
        name: station
        referencedColumnName: id
    measurementType:
      targetEntity: MeasurementType
      inversedBy: measurements
      joinColumn:
        name: measurementType
        referencedColumnName: id
