Zubi\DeviceBundle\Entity\Measurement:
  type: entity
  table: Pomiary
  fields:
    id:
      type: integer
      id: true
      column: Id
      generator:
        strategy: AUTO
    timestamp:
      type: datetime
      column: Czas
    value:
      type: float
      column: Wartosc
  lifecycleCallbacks: {  }
  manyToOne:
    station:
      targetEntity: Station
      inversedBy: measurements
      joinColumn:
        name: Id_Stacji
        referencedColumnName: id
    measurementType:
      targetEntity: MeasurementType
      inversedBy: measurements
      joinColumn:
        name: Id_Typu_Pomiaru
        referencedColumnName: id
