Zubi\DeviceBundle\Entity\MeasurementType:
  type: entity
  table: Typy_pomiarow
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
    unit:
      type: string
      length: 255
  lifecycleCallbacks: {  }
  oneToMany:
    measurements:
      targetEntity: Measurement
      mappedBy: measurementType
